export interface TutorialStep {
  id: string;
  title: string;
  description: string;
  targetSelector: string; // CSS selector for the element to highlight
  position: 'top' | 'bottom' | 'left' | 'right';
  action?: 'click' | 'none'; // Whether user needs to click the element
}

export const tutorialSteps: TutorialStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to SystemA!',
    description: 'SystemA helps you design and document system architectures with a focus on failure modes and recovery strategies. Let\'s take a quick tour!',
    targetSelector: 'body',
    position: 'bottom',
    action: 'none',
  },
  {
    id: 'canvas',
    title: 'The Architecture Canvas',
    description: 'This is where you design your system. You can drag components around, connect them, and visualize your entire architecture. Use left-click to pan, shift+drag to select multiple components.',
    targetSelector: '.react-flow',
    position: 'top',
    action: 'none',
  },
  {
    id: 'add-component',
    title: 'Adding Components',
    description: 'Click here to add a new component to your architecture. You can also right-click anywhere on the canvas to add a component at that position.',
    targetSelector: '.react-flow__panel button:has(> .lucide-plus)',
    position: 'bottom',
    action: 'none',
  },
  {
    id: 'component-types',
    title: 'Component Types',
    description: 'SystemA supports 6 component types: API (REST/GraphQL endpoints), Database (SQL/NoSQL stores), Worker (background jobs/processing), Queue (message queues like Kafka/SQS), External Service (third-party dependencies), and Human Process (manual workflows). Choose the type that best represents each part of your system.',
    targetSelector: '.react-flow__node',
    position: 'right',
    action: 'none',
  },
  {
    id: 'connections',
    title: 'Creating Connections',
    description: 'Connect components by dragging from the edge of one component to another. Connections represent data flow and dependencies. Click on a connection to view or edit its details.',
    targetSelector: '.react-flow__edge',
    position: 'top',
    action: 'none',
  },
  {
    id: 'component-metadata',
    title: 'Component Metadata',
    description: 'Click on a component to see its details panel. Here you can set: Type (API, Database, etc.), Owner (team/person responsible), Environment (production, staging, dev), Criticality (High/Medium/Low - affects color coding), Description, Inputs (data/requests received), Outputs (data/responses sent), Dependencies (what it relies on), and most importantly - Failure Modes and Recovery Strategies.',
    targetSelector: '.react-flow__node',
    position: 'right',
    action: 'click',
  },
  {
    id: 'failure-modes',
    title: 'Failure Modes',
    description: 'This is where SystemA shines! In the Failure Modes section, document what can go wrong: service crashes, network timeouts, database deadlocks, API rate limits, etc. For each failure, specify Impact (what breaks), Probability (how likely), and Detection (how you know it happened). This helps you plan for resilience.',
    targetSelector: '[data-tutorial-section="failure-modes"]',
    position: 'right',
    action: 'none',
  },
  {
    id: 'recovery-strategies',
    title: 'Recovery Strategies',
    description: 'For each failure mode, define recovery: Is it Automatic (circuit breakers, retries, auto-scaling) or Manual (paging engineers)? What are the Steps to recover? What is the Recovery Time Objective (RTO)? Document fallback behaviors, monitoring alerts, and runbooks. Good recovery documentation turns outages into non-events.',
    targetSelector: '[data-tutorial-section="recovery-strategies"]',
    position: 'right',
    action: 'none',
  },
  {
    id: 'simulation',
    title: 'Failure Simulation',
    description: 'Click "Start Simulation" to enter simulation mode. In this mode, you can click components to toggle failure states and see how it affects dependent components.',
    targetSelector: '.react-flow__panel button:has(> .lucide-play)',
    position: 'bottom',
    action: 'none',
  },
  {
    id: 'architecture-name',
    title: 'Editing Architecture Name',
    description: 'Click on the architecture name in the header to edit it. This name is used when saving and exporting your architecture.',
    targetSelector: 'header span[title="Click to edit name"]',
    position: 'bottom',
    action: 'none',
  },
  {
    id: 'save',
    title: 'Saving Your Work',
    description: 'Click the Save button to save your architecture to the cloud. Your work is automatically associated with your account and can be accessed from anywhere.',
    targetSelector: 'header button[title="Save"]',
    position: 'bottom',
    action: 'none',
  },
  {
    id: 'open',
    title: 'Opening Saved Architectures',
    description: 'Click Open to view and load your previously saved architectures. You can also see architectures shared with you by collaborators.',
    targetSelector: 'header button[title="Open"]',
    position: 'bottom',
    action: 'none',
  },
  {
    id: 'details',
    title: 'Architecture Details',
    description: 'View high-level details about your architecture including name, description, problem statement, constraints, assumptions, and status.',
    targetSelector: 'header button[title="Details"]',
    position: 'bottom',
    action: 'none',
  },
  {
    id: 'collaborate',
    title: 'Collaboration',
    description: 'Share your architecture with team members! Add collaborators by email, set their permissions (Owner, Editor, Commenter, Viewer), or create public links.',
    targetSelector: 'header button[title="Collaborate"]',
    position: 'bottom',
    action: 'none',
  },
  {
    id: 'export',
    title: 'Exporting',
    description: 'Export your architecture as a JSON file for backup, version control, or sharing offline.',
    targetSelector: 'header button[title="Export"]',
    position: 'bottom',
    action: 'none',
  },
  {
    id: 'controls',
    title: 'Canvas Controls',
    description: 'Use these controls to zoom in/out, fit the view, and reset the canvas. You can also use mouse wheel to zoom and drag to pan.',
    targetSelector: '.react-flow__controls',
    position: 'right',
    action: 'none',
  },
  {
    id: 'minimap',
    title: 'Minimap',
    description: 'The minimap shows an overview of your entire architecture. Use it to navigate large diagrams quickly. Component colors indicate criticality (red=high, yellow=medium, green=low).',
    targetSelector: '.react-flow__minimap',
    position: 'left',
    action: 'none',
  },
  {
    id: 'context-menu',
    title: 'Component Actions',
    description: 'Right-click on components to access quick actions: Duplicate (copies the component and its connections), Edit (opens metadata panel), or Delete (removes with animation).',
    targetSelector: 'body',
    position: 'bottom',
    action: 'none',
  },
  {
    id: 'complete',
    title: 'You\'re All Set!',
    description: 'You now know the basics of SystemA. Start by exploring the demo architecture, or create your own from scratch. Remember: good architecture documentation includes failure modes and recovery strategies!',
    targetSelector: 'body',
    position: 'bottom',
    action: 'none',
  },
];
